version: '1.02'
links:
    item1:
        name: 'environment'
        item: '.env'
    item2:
        name: 'database'
        item: 'config/database.yml'
    item3:
        name: 'datacollectors'
        item: 'config/datacollectors.yml'
    item3:
        name: 'storage'
        item: 'config/storage.yml'
    item4:
        name: 'welcome-message'
        item: 'public/welcome-message.md'
    item5:
        name: 'log'
        item: 'log'
    item6:
        name: 'tmp'
        item: 'tmp'
    item7:
        name: 'uploads'
        item: 'uploads'
    item8:
        name: 'webpacker packs'
        item: 'public/packs'
    item9:
        name: 'node assets'
        item: 'public/assets'
    items10:
        name: 'secrets'
        item: 'config/secrets.yml'
