version: '3'
services:
    db:
        image: 'postgres:14'
        restart: unless-stopped
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_USER=postgres
            - PSTGRES_PASSWORD=postgres

    eln:
        image: 'chemotion-build:latest-eln'
        depends_on:
            - db
        environment:
            - THOR_SILENCE_DEPRECATION=1
        volumes:
          - ./init.sh:/run/eln/init.sh
        entrypoint: "/bin/bash -c 'while true; do /usr/bin/sleep 1; done'"


# Persist database information after container is removed
volumes:
    db_data:
