version: '3'
services:
    db:
        image: 'postgres:latest'
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_USER=postgres
            - PSTGRES_PASSWORD=postgres

    eln:
        build: .
        depends_on:
            - db
        volumes:
            - ./shared:/shared
        expose:
            - '4000'
            - '4001'
